In [10]:
import numpy as cd
p=cd.array([22,16.5,"hi",True],dtype=object)
print(p)

[22 16.5 'hi' True]


In [12]:
import numpy as vd
w=vd.array([[True],[False]],dtype=int)
print(w)

[[1]
 [0]]


In [8]:
import numpy as np
e=np.zeros((6,5),dtype=int)
print(e)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [9]:
import numpy as nn
f=nn.empty((1,2))
print(f)

[[-2.00000000e+000  1.26370716e-314]]


In [37]:
import numpy as nj
d=nj.arange(6,1,-1)
print(d)

[6 5 4 3 2]


In [47]:
import numpy as mk
r=mk.eye(2)
print(r)

[[1. 0.]
 [0. 1.]]


In [15]:
import numpy as ij
l=ij.identity(3,dtype=int)
print(l)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [10]:
import numpy as re
p=re.full((4,4),"qungu")
print(p)

[['qungu' 'qungu' 'qungu' 'qungu']
 ['qungu' 'qungu' 'qungu' 'qungu']
 ['qungu' 'qungu' 'qungu' 'qungu']
 ['qungu' 'qungu' 'qungu' 'qungu']]


In [45]:
import numpy as we
p=we.random.seed(3)
o=we.random.rand(1)
print(o)
print(p)

[0.5507979]
None


In [40]:
import numpy as qw
b=qw.random.randint(4)
print(b)

1


In [69]:
import numpy as no
e=no.array([[2,4,6],[4,6,10]])
d=e.shape
print(d)


(2, 3)


In [79]:
import numpy as mp
d=mp.array([[1,2,3],[2,3,4]],dtype=int)
f=d.size
print(f)


6


In [80]:
import numpy as dr
r=dr.array([[1,2],[2,3]])
e=r.ndim
print(e)
print(r.dtype)
print(r.itemsize)

2
int64
8
